version: '2'
services:
  houseapplication-mongodb:
    image: mongo:4.0.16
    ports:
      - '27017:27017'
    command: mongos --configdb houseapplication-mongodb-config
  houseapplication-mongodb-node:
    build:
      context: .
      dockerfile: mongodb/MongoDB.Dockerfile
    command: mongod --replSet rs1 --noprealloc --smallfiles
  houseapplication-mongodb-config:
    image: mongo:4.0.16
    container_name: houseapplication-mongodb-config
    command: mongod --noprealloc --smallfiles --configsvr --dbpath /data/db
